name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: Cabin
      fonts:
      - asset: assets/fonts/Cabin-Regular.otf
      - asset: assets/fonts/Cabin-Bold.otf
      - asset: assets/fonts/Cabin-BoldItalic.otf
      - asset: assets/fonts/Cabin-Italic.otf
      - asset: assets/fonts/Cabin-Medium.otf
      - asset: assets/fonts/Cabin-MediumItalic.otf
      - asset: assets/fonts/Cabin-SemiBold.otf
      - asset: assets/fonts/Cabin-SemiBoldItalic.otf
